# Generated by Django 4.2.9 on 2024-01-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0005_company_remove_client_created_by_delete_logentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='container',
            field=models.ForeignKey(default='ef30270f-c15f-4277-9471-e48b721edbff', on_delete=django.db.models.deletion.CASCADE, to='mms_api.container'),
            preserve_default=False,
        ),
    ]
