# Generated by Django 4.2.9 on 2024-01-16 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms_api', '0006_company_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('price_in_dinar', models.FloatField()),
                ('price_in_dollar', models.FloatField()),
                ('description', models.TextField(max_length=2000)),
                ('received_from', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.company')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('mr', models.CharField(max_length=255)),
                ('price_in_dinar', models.FloatField()),
                ('price_in_dollar', models.FloatField()),
                ('description', models.TextField(max_length=2000)),
                ('out_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.company')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms_api.container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_withdrawer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicetype',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceType',
        ),
    ]
