# Generated by Django 4.2.9 on 2024-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0007_deposit_withdraw_remove_invoicetype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
