# Generated by Django 4.2.9 on 2024-01-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0008_alter_company_title_alter_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
