# Generated by Django 4.2.9 on 2024-01-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0012_withdraw_withdraw_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mms_api.withdrawtype'),
        ),
    ]
