# Generated by Django 4.2.9 on 2024-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0013_alter_deposit_received_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='received_from',
            field=models.CharField(max_length=255),
        ),
    ]
