# Generated by Django 4.2.9 on 2024-01-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0015_endpointlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointlog',
            name='response_body',
        ),
    ]
