# Generated by Django 4.2.9 on 2024-01-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0016_remove_endpointlog_response_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointlog',
            name='request_body',
        ),
    ]
