# Generated by Django 4.2.9 on 2024-01-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0017_remove_endpointlog_request_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointlog',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
