# Generated by Django 4.2.9 on 2024-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0019_alter_withdrawtype_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndpointLog',
        ),
    ]
