# Generated by Django 4.2.9 on 2024-02-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0020_delete_endpointlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'الشركات'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name_plural': 'القاصات'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name_plural': 'الايداعات'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name_plural': 'الصرفيات'},
        ),
        migrations.AlterModelOptions(
            name='withdrawtype',
            options={'verbose_name_plural': 'القيود'},
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='mr',
        ),
    ]
