# Generated by Django 4.2.9 on 2024-02-12 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms_api', '0021_alter_company_options_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='record_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='record_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
