# Generated by Django 4.2.9 on 2024-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0022_company_supervisor_deposit_record_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={},
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
