# Generated by Django 4.2.9 on 2024-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0023_alter_deposit_options_deposit_deposit_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name_plural': 'الايداعات'},
        ),
        migrations.AddField(
            model_name='withdraw',
            name='deposit_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
