# Generated by Django 4.2.9 on 2024-02-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0024_alter_deposit_options_withdraw_deposit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='deposit_number',
            new_name='withdraw_number',
        ),
    ]
