# Generated by Django 4.2.9 on 2024-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0025_rename_deposit_number_withdraw_withdraw_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='withdraw_documents/'),
        ),
    ]
