# Generated by Django 4.2.9 on 2024-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_api', '0026_withdraw_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='withdraw_documents/'),
        ),
    ]
